<!DOCTYPE html>
<html>
<head>
  <title>How to Lie with Degree Days</title>
  <meta charset="utf-8">
  <meta name="description" content="How to Lie with Degree Days">
  <meta name="author" content="David Lindelöf">
  <meta name="generator" content="slidify" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/default.css" media="all" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/phone.css" 
    media="only screen and (max-device-width: 480px)" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/slidify.css" >
  <link rel="stylesheet" href="libraries/highlighters/highlight.js/css/tomorrow.css" />
  <base target="_blank"> <!-- This amazingness opens all links in a new tab. -->  <link rel=stylesheet href="./assets/css/ribbons.css"></link>

  
  <!-- Grab CDN jQuery, fall back to local if offline -->
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>
  <script>window.jQuery || document.write('<script src="libraries/widgets/quiz/js/jquery.js"><\/script>')</script> 
  <script data-main="libraries/frameworks/io2012/js/slides" 
    src="libraries/frameworks/io2012/js/require-1.0.8.min.js">
  </script>
  
  

</head>
<body style="opacity: 0">
  <slides class="layout-widescreen">
    
    <!-- LOGO SLIDE -->
        <slide class="title-slide segue nobackground">
  <hgroup class="auto-fadein">
    <h1>How to Lie with Degree Days</h1>
    <h2></h2>
    <p>David Lindelöf<br/></p>
  </hgroup>
  <article></article>  
</slide>
    

    <!-- SLIDES -->
    <slide class="" id="slide-1" style="background:;">
  <hgroup>
    <h2>The problem</h2>
  </hgroup>
  <article data-timings="">
    <p>Suppose you invest in a better insulation for your house.
<em>How then will you know whether your investement was effective?</em></p>

<p>Three options:</p>

<ul>
<li>Use the <a href="http://en.wikipedia.org/wiki/International_performance_measurement_and_verification_protocol">International performance measurement and verification protocol</a>

<ul>
<li>requires historic data, takes a very long time to perform</li>
</ul></li>
<li>Measure your energy signature before and after the installation

<ul>
<li>requires simultaneous measurement of outdoor temperatures</li>
</ul></li>
<li>Measure your energy use, and correlate with degree-days in your region

<ul>
<li>very easy to implement, usually the first choice of energy consultants</li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="class" id="id" style="background:;">
  <hgroup>
    <h2>The danger with degree-days</h2>
  </hgroup>
  <article data-timings="">
    <p>Degree-days are published by local authorities and are supposedly a reliable indicator of how
much energy a building is going to need to keep its indoor temperature.</p>

<p>The degree-days for a given day are loosely defined as:</p>

<p>\[DD = max(0, t_\text{base} - \overline{t_\text{out}})\]</p>

<p>where \(t_\text{base}\) is the so-called <em>baseline temperature</em>, i.e. the average outdoor temperature
above which the internal and free gains of a building make extra heating unnecessary, and \(\overline{t_\text{out}}\) is the mean outdoor temperature for that day.</p>

<p>Then if a building needs \(E\) kWh in a day with \(DD\) degree-days, its energy performance will be
given as \(\frac{E}{DD}\). The lower this value, the better.</p>

<p>The problem is that \(DD\) depends on \(t_\text{base}\), which is chosen by the local
authority but should be different from building to building.</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="class" id="id" style="background:;">
  <hgroup>
    <h2>Example</h2>
  </hgroup>
  <article data-timings="">
    <p>Your house&#39;s real baseline temperature is 20ºC. Degree-days published in your region
assume a baseline temperature of 18ºC. You want to estimate how much energy your house
will need at 0ºC outdoor temperature, before and after installing a new insulation.</p>

<p>Before installing the new insulation, you measure your building&#39;s energy consumption during a day
at 100 kWh, with an average outdoor temperature of 10ºC.</p>

<p>After installing it, you measure the energy again for one day and find that you require
25 kWh during a day with 15ºC average outdoor temperature.</p>

<p>So how much energy would your house need at 0ºC, with or without degree-days,
before and after the new insulation?</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="class" id="id" style="background:;">
  <hgroup>
    <h2>Degree-days prediction</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">dd.baseline &lt;- 18
true.baseline &lt;- 20
d &lt;- data.frame(Energy=c(100,25), Degrees=c(10,15), System=c(&quot;Before&quot;, &quot;After&quot;))
d
</code></pre>

<pre><code>##   Energy Degrees System
## 1    100      10 Before
## 2     25      15  After
</code></pre>

<pre><code class="r">dd.performance &lt;- by(d, d$System, function(x) x$Energy / (dd.baseline - x$Degrees))
as.numeric(dd.performance * dd.baseline)
</code></pre>

<pre><code>## [1] 150 225
</code></pre>

<p>The degree-days method predicts 225 kWh and 150 kWh consumption at 0ºC, before
and after the new insulation, or an improvement of 33%.</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="class" id="id" style="background:;">
  <hgroup>
    <h2>True prediction</h2>
  </hgroup>
  <article data-timings="">
    <p>Here is the prediction when using the building&#39;s true baseline:</p>

<pre><code class="r">true.performance &lt;- by(d, d$System, function(x) x$Energy / (true.baseline - x$Degrees))
as.numeric(true.performance * true.baseline)
</code></pre>

<pre><code>## [1] 100 200
</code></pre>

<p>So in reality, the building will use 200 kWh and 100 kWh at 0ºC, before and after the
new installation, or an improvement of 50%, not merely 33%.</p>

<p><a href="https://dlindelof.shinyapps.io/degreedays/">This Shiny app</a> will let you play with different values for the degree-days baseline
and the true baseline, and see how this affects the predicted energy savings with
a set of simulated data.</p>

  </article>
  <!-- Presenter Notes -->
</slide>

    <slide class="backdrop"></slide>
  </slides>
  <div class="pagination pagination-small" id='io2012-ptoc' style="display:none;">
    <ul>
      <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=1 title='The problem'>
         1
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=2 title='The danger with degree-days'>
         2
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=3 title='Example'>
         3
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=4 title='Degree-days prediction'>
         4
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=5 title='True prediction'>
         5
      </a>
    </li>
  </ul>
  </div>  <!--[if IE]>
    <script 
      src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js">  
    </script>
    <script>CFInstall.check({mode: 'overlay'});</script>
  <![endif]-->
</body>
  <!-- Load Javascripts for Widgets -->
  
  <!-- MathJax: Fall back to local if CDN offline but local image fonts are not supported (saves >100MB) -->
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        processEscapes: true
      }
    });
  </script>
  <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <!-- <script src="https://c328740.ssl.cf1.rackcdn.com/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script> -->
  <script>window.MathJax || document.write('<script type="text/x-mathjax-config">MathJax.Hub.Config({"HTML-CSS":{imageFont:null}});<\/script><script src="libraries/widgets/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"><\/script>')
</script>
<!-- LOAD HIGHLIGHTER JS FILES -->
  <script src="libraries/highlighters/highlight.js/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <!-- DONE LOADING HIGHLIGHTER JS FILES -->
   
  </html>